sudo: required
language: scala
# https://github.com/nativelibs4java/scalaxy-streams/commit/01ffbadeece7e2db8b21373fcdc25298845869d4
sudo: true
scala:
  - 2.11.8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - geoip-resources
services:
  - docker
before_install:
  - docker pull hseeberger/scala-sbt
script:
#  - make travis
  - docker run -v ${PWD}/geoip-resources:/af/geoip-resources -v ${HOME}/.sbt/boot/:/root/.sbt/boot/ -v ${HOME}/.m2:/root/.m2 -v ${HOME}/.ivy2:/root/.ivy2/cache -v ${PWD}:/af -it -w=/af hseeberger/scala-sbt sbt test it:test
jdk:
  - oraclejdk8
